//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kodlama1_mvcEntities : DbContext
    {
        public kodlama1_mvcEntities()
            : base("name=kodlama1_mvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userlar> userlar { get; set; }
        public virtual DbSet<roller> roller { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<sepet> sepet { get; set; }
    }
}
