//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepet
    {
        public int sepetid { get; set; }
        public int sepeturunid { get; set; }
        public int sepetuserid { get; set; }
        public int sepeturunadet { get; set; }
    }
}
